name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types:
      - post-bump-build

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: Download Dalamud Latest
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip -DestinationPath "$env:AppData\XIVLauncherCN\Addon\Hooks\dev"
          Expand-Archive -Force latest.zip -DestinationPath "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Restore NuGet Packages
        shell: pwsh
        run: dotnet restore Teleport\Teleport.csproj

      - name: Build Plugin
        shell: pwsh
        run: dotnet build --no-restore -c Release-Pro Teleport\Teleport.csproj
